listen_on: ':19311'
prometheus:
  url: 'http://132.252.128.109:19090'
es:
  urls: ['http://10.1.236.157:9200/']
  index: 'node-metrics-${+yyyy.MM}'
kafka:
  brokers: ['132.224.71.10:16667','132.224.71.11:16667','132.224.71.12:16667','132.224.71.13:16667','132.224.71.14:16667']
  topic_paas: 'paas-component-metric'
  topic_e2e: 'paas-component-metric-e2e'
  group: 'paasMetric'
promql:
  instance_id: 
    label: 'instance'
    regex: '(.*):.*'
    replacement: '$1'
    is_ip_port: true
  querys:
    - metric: 'httpconnections'
      query: 'sum by (instance,cluster)(nginx_http_connections)'
add_fields:
  api_url: '' 