listen_on: ':19311'
prometheus:
  url: 'http://132.252.128.110:19090'
  name: 'PS.REDIS'
  comptype: '170201'
kafka:
  brokers: ['127.0.0.1:9092'  ]
  topicpaas: 'paas-component-metric'
  topice2e: 'testNJ'
  group: 'paasMetric'
promql:
  instance_id: 
    label: 'addr'
    regex: '(.*):.*'
    replacement: '$1'
    is_ip_port: true
  querys:
    - metric: 'redis_up'
      query: 'sum by(instance,addr,cluster,cluster_id,cluster_type) (redis_up)'
      metriccode: '30202623260001'
      metrictype: '1'
    - metric: 'redis_instance_info'
      query: 'sum by(instance,addr,cluster,cluster_id,cluster_type) (redis_instance_info)'
      metriccode: '30202623260003'
      metrictype: '1'
    - metric: 'redis_connected_clients'
      query: 'sum by(instance,addr,cluster,cluster_id,cluster_type) (redis_connected_clients)'
      metriccode: '30202623260004'
      metrictype: '1'
    - metric: 'redis_blocked_clients'
      query: 'sum by(instance,addr,cluster,cluster_id,cluster_type) (redis_blocked_clients)'
      metriccode: '30202623260005'
      metrictype: '1'
    - metric: 'redis_commands_processed_total'
      query: 'sum by(instance,addr,cluster,cluster_id,cluster_type) (redis_commands_processed_total)'
      metriccode: '30202624260011'
      metrictype: '2'
    - metric: 'redis_memory_used_bytes / redis_config_maxmemory'
      query: 'sum by(instance,addr,cluster,cluster_id,cluster_type) (redis_memory_used_bytes / redis_config_maxmemory)'
      metriccode: '30202624260001'
      metrictype: '2'
